# include:
  # - backend/compose.yaml
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    command: vite
    develop:
      watch:
        - action: sync
          path: frontend/
          target: /app
          ignore:
            - node_modules/
        - action: sync
          path: ./frontend/package.json
          target: package.json
    depends_on:
      - backend

  backend:
    build: ./backend
    # volumes:
    #   - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: backend/
          target: /app

networks:
  keycoders:
    driver: bridge

volumes:
  data:
