services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    command: vite
    develop:
      watch:
        - action: sync
          path: frontend/
          target: /app
          ignore:
            - node_modules/
        - action: sync
          path: ./frontend/package.json
          target: /app/package.json
    # depends_on:
      # - backend

  # backend:
  #   build: ./backend
  #   ports:
  #     - "8080:8080"
